### ISSUE TITLE
SVGDesc has no attribute 'values'

### ISSUE THREAD

**Issue by osresearch** [abey79/vpype#124]
When processing SVG files from https://plotter.vision/ the `<desc>` tag appears to be causing a problem for vpype:
```
% vpype --version
vpype 1.1.0
% vpype read  ~/Downloads/bunny-3d.svg 
/home/hudson/.local/lib/python3.6/site-packages/matplotlib/backends/qt_editor/figureoptions.py:11: MatplotlibDeprecationWarning: 
The support for Qt4  was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
  from matplotlib.backends.qt_compat import QtGui
Traceback (most recent call last):
  File "/home/hudson/.local/bin/vpype", line 11, in <module>
    sys.exit(cli())
  File "/home/hudson/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/hudson/.local/lib/python3.6/site-packages/vpype_cli/cli.py", line 75, in main
    return super().main(args=preprocess_argument_list(args), **extra)
  File "/home/hudson/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/hudson/.local/lib/python3.6/site-packages/click/core.py", line 1290, in invoke
    return _process_result(rv)
  File "/home/hudson/.local/lib/python3.6/site-packages/click/core.py", line 1224, in _process_result
    value = ctx.invoke(self.result_callback, value, **ctx.params)
  File "/home/hudson/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/hudson/.local/lib/python3.6/site-packages/vpype_cli/cli.py", line 131, in process_pipeline
    execute_processors(processors)
  File "/home/hudson/.local/lib/python3.6/site-packages/vpype_cli/cli.py", line 215, in execute_processors
    state = proc(state)
  File "/home/hudson/.local/lib/python3.6/site-packages/vpype/decorators.py", line 150, in global_processor
    state.document = f(state.document, *args, **kwargs)
  File "/home/hudson/.local/lib/python3.6/site-packages/vpype_cli/read.py", line 189, in read
    default_height=height,
  File "/home/hudson/.local/lib/python3.6/site-packages/vpype/io.py", line 290, in read_multilayer_svg
    _extract_paths(svg, recursive=False), quantization, simplify, parallel
  File "/home/hudson/.local/lib/python3.6/site-packages/vpype/io.py", line 177, in _extract_paths
    if elem.values.get("visibility", "") in ("hidden", "collapse"):
AttributeError: 'SVGDesc' object has no attribute 'values'
```

**Comment by abey79** [comment]
Indeed, I can reproduce. I'll look into asap. In the mean time the workaround consists of editing the `<desc>` tag away, as you have certainly figured out.
