### ISSUE TITLE
bug: AttributeError: 'Viewbox' object has no attribute 'element_width'

### ISSUE THREAD

**Issue by scruss** [abey79/vpype#140]
Installed via [Linux](https://vpype.readthedocs.io/en/stable/install.html#linux) venv method.

Running on Ubuntu x86_64.

Every SVG I've tried failed the same way:

    vpype read tri.svg scaleto 19cm 27.7cm write -p a4 -c output.svg
    Traceback (most recent call last):
      File "/home/scruss/Documents/python/vpype_venv/bin/vpype", line 8, in <module>
        sys.exit(cli())
      File "/home/scruss/Documents/python/vpype_venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
        return self.main(*args, **kwargs)
      File "/home/scruss/Documents/python/vpype_venv/lib/python3.8/site-packages/vpype_cli/cli.py", line 74, in main
        return super().main(args=preprocess_argument_list(args), **extra)
      File "/home/scruss/Documents/python/vpype_venv/lib/python3.8/site-packages/click/core.py", line 782, in main
        rv = self.invoke(ctx)
      File "/home/scruss/Documents/python/vpype_venv/lib/python3.8/site-packages/click/core.py", line 1290, in invoke
        return _process_result(rv)
      File "/home/scruss/Documents/python/vpype_venv/lib/python3.8/site-packages/click/core.py", line 1224, in _process_result
        value = ctx.invoke(self.result_callback, value, **ctx.params)
      File "/home/scruss/Documents/python/vpype_venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
        return callback(*args, **kwargs)
      File "/home/scruss/Documents/python/vpype_venv/lib/python3.8/site-packages/vpype_cli/cli.py", line 128, in process_pipeline
        execute_processors(processors)
      File "/home/scruss/Documents/python/vpype_venv/lib/python3.8/site-packages/vpype_cli/cli.py", line 212, in execute_processors
        state = proc(state)
      File "/home/scruss/Documents/python/vpype_venv/lib/python3.8/site-packages/vpype/decorators.py", line 150, in global_processor
        state.document = f(state.document, *args, **kwargs)
      File "/home/scruss/Documents/python/vpype_venv/lib/python3.8/site-packages/vpype_cli/read.py", line 182, in read
        read_multilayer_svg(
      File "/home/scruss/Documents/python/vpype_venv/lib/python3.8/site-packages/vpype/io.py", line 325, in read_multilayer_svg
        width = svg.viewbox.element_width or default_width
    AttributeError: 'Viewbox' object has no attribute 'element_width'

Also tried with Inkscape simple straight lines and converted HP-GL to SVG via hp2xx. No output at all.

**Comment by abey79** [comment]
Thanks for the report @scruss. Could you provide one of the SVG files that causes this issue?

**Comment by scruss** [comment]
Sure: from your own repo: https://github.com/abey79/vpype/blob/master/examples/bc_template.svg

    vpype read bc_template.svg scaleto 19cm 27.7cm write -p a4 -c output.svg
    Traceback (most recent call last):
      File "/home/scruss/Documents/python/vpype_venv/bin/vpype", line 8, in <module>
        sys.exit(cli())
      File "/home/scruss/Documents/python/vpype_venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
        return self.main(*args, **kwargs)
      File "/home/scruss/Documents/python/vpype_venv/lib/python3.8/site-packages/vpype_cli/cli.py", line 74, in main
        return super().main(args=preprocess_argument_list(args), **extra)
      File "/home/scruss/Documents/python/vpype_venv/lib/python3.8/site-packages/click/core.py", line 782, in main
        rv = self.invoke(ctx)
      File "/home/scruss/Documents/python/vpype_venv/lib/python3.8/site-packages/click/core.py", line 1290, in invoke
        return _process_result(rv)
      File "/home/scruss/Documents/python/vpype_venv/lib/python3.8/site-packages/click/core.py", line 1224, in _process_result
        value = ctx.invoke(self.result_callback, value, **ctx.params)
      File "/home/scruss/Documents/python/vpype_venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
        return callback(*args, **kwargs)
      File "/home/scruss/Documents/python/vpype_venv/lib/python3.8/site-packages/vpype_cli/cli.py", line 128, in process_pipeline
        execute_processors(processors)
      File "/home/scruss/Documents/python/vpype_venv/lib/python3.8/site-packages/vpype_cli/cli.py", line 212, in execute_processors
        state = proc(state)
      File "/home/scruss/Documents/python/vpype_venv/lib/python3.8/site-packages/vpype/decorators.py", line 150, in global_processor
        state.document = f(state.document, *args, **kwargs)
      File "/home/scruss/Documents/python/vpype_venv/lib/python3.8/site-packages/vpype_cli/read.py", line 182, in read
        read_multilayer_svg(
      File "/home/scruss/Documents/python/vpype_venv/lib/python3.8/site-packages/vpype/io.py", line 325, in read_multilayer_svg
        width = svg.viewbox.element_width or default_width
    AttributeError: 'Viewbox' object has no attribute 'element_width'

**Comment by abey79** [comment]
Thanks @scruss, problem identified: new version of svgelements is breaking `read`. This is fixed in release 1.2.1.
