### ISSUE TITLE
Contribution page shows deprecated Poetry installation instructions

### ISSUE THREAD

**Issue by johnbentcope** [abey79/vpype#517]
The contributing.rst file shows the usage of curl piped to a python interpreter, while pipx is the preferred method of installation.

**Comment by OzHawk** [comment]
Is `pipx` the preferred method of installing the develpment environment?
I would like to start contributing to the development/maintenance of the project, but need some pointers regarding setting up the development environment.
I tried following the instructions on the "Contributions" page and got this error at the first step.
```
:~$ curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
Retrieving Poetry metadata
Traceback (most recent call last):
  File "<stdin>", line 1119, in <module>
  File "<stdin>", line 1115, in main
  File "<stdin>", line 351, in run
  File "<stdin>", line 414, in get_version
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 20: ordinal not in range(128)
```

**Comment by abey79** [comment]
Yeah, the first line (with curl) is for installing [Poetry](https://python-poetry.org), which is what vpype uses for packaging and dependency management and is required to setup a dev environment. 

That link is indeed outdated. The proper "curl" link is this now:

```
curl -sSL https://install.python-poetry.org | python3 -
```

Poetry may also be installed using pipx, though it's listed as "[not recommended alternative installation](https://python-poetry.org/docs/#installing-with-pipx)". The main reason for this, I assume, is because then `poetry self update` won't work (`pipx upgrade poetry` must be used instead).

I'll update that link later today.

**Comment by OzHawk** [comment]
Not sure if this is supposed to happen, but the poetry install step failed because `pillow` was not installed.
```poetry install
Installing dependencies from lock file

Package operations: 45 installs, 0 updates, 0 removals

  • Installing pyparsing (3.0.9)
  • Installing packaging (21.3)
  • Installing six (1.16.0)
  • Installing tomli (2.0.1)
  • Installing typing-extensions (4.3.0)
  • Installing attrs (21.4.0)
  • Installing cycler (0.11.0)
  • Installing fonttools (4.33.3)
  • Installing iniconfig (1.1.1)
  • Installing kiwisolver (1.4.3)
  • Installing markupsafe (2.1.1)
  • Installing numpy (1.23.0)
  • Installing pillow (9.2.0): Failed

  EnvCommandError

  Command ['/home/mike/Documents/Projects/plotter_files/plottertools_venv/bin/pip', 'install', '--no-deps', '/home/mike/.cache/pypoetry/artifacts/d5/ef/90/d3e7af61c9a736d9ca32bd09c4fa0ada8c54eab7dbc5a7b137a28a1302/Pillow-9.2.0-cp38-cp38-manylinux_2_28_x86_64.whl'] errored with the following return code 1, and output: 
  ERROR: Pillow-9.2.0-cp38-cp38-manylinux_2_28_x86_64.whl is not a supported wheel on this platform.
  

  at ~/.local/share/pypoetry/venv/lib/python3.8/site-packages/poetry/utils/env.py:1195 in _run
      1191│                 output = subprocess.check_output(
      1192│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1193│                 )
      1194│         except CalledProcessError as e:
    → 1195│             raise EnvCommandError(e, input=input_)
      1196│ 
      1197│         return decode(output)
      1198│ 
      1199│     def execute(self, bin, *args, **kwargs):

  • Installing pluggy (1.0.0)
  • Installing py (1.11.0)
  • Installing python-dateutil (2.8.2)
  • Installing setuptools-scm (7.0.4)
```
I manually installed `pillow` using pip and then retried and it worked.

**Comment by OzHawk** [comment]
I then tested the setup by running the vpype tests and had 4 fail.  
```poetry run pytest
========================================================== test session starts ==========================================================
platform linux -- Python 3.8.10, pytest-7.1.2, pluggy-1.0.0
Matplotlib: 3.5.2
Freetype: 2.6.1
benchmark: 3.4.1 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /home/mike/Documents/Projects/plotters/vpype, configfile: pyproject.toml
plugins: mpl-0.16.0, benchmark-3.4.1, cov-3.0.0
collected 1289 items / 4 errors                                                                                                         

================================================================ ERRORS =================================================================
_______________________________________________ ERROR collecting tests/test_benchmarks.py _______________________________________________
ImportError while importing test module '/home/mike/Documents/Projects/plotters/vpype/tests/test_benchmarks.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_benchmarks.py:7: in <module>
    from vpype_viewer import ViewMode, render_image
vpype_viewer/__init__.py:6: in <module>
    from .engine import *
vpype_viewer/engine.py:10: in <module>
    import moderngl as mgl
E   ModuleNotFoundError: No module named 'moderngl'
__________________________________________________ ERROR collecting tests/test_show.py __________________________________________________
ImportError while importing test module '/home/mike/Documents/Projects/plotters/vpype/tests/test_show.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_show.py:9: in <module>
    import vpype_viewer
vpype_viewer/__init__.py:6: in <module>
    from .engine import *
vpype_viewer/engine.py:10: in <module>
    import moderngl as mgl
E   ModuleNotFoundError: No module named 'moderngl'
------------------------------------------------------------ Captured stderr ------------------------------------------------------------
WARNING:matplotlib.font_manager:Matplotlib is building the font cache; this may take a moment.
__________________________________________________ ERROR collecting tests/test_text.py __________________________________________________
ImportError while importing test module '/home/mike/Documents/Projects/plotters/vpype/tests/test_text.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_text.py:6: in <module>
    from vpype_viewer import ImageRenderer, UnitType
vpype_viewer/__init__.py:6: in <module>
    from .engine import *
vpype_viewer/engine.py:10: in <module>
    import moderngl as mgl
E   ModuleNotFoundError: No module named 'moderngl'
_________________________________________________ ERROR collecting tests/test_viewer.py _________________________________________________
ImportError while importing test module '/home/mike/Documents/Projects/plotters/vpype/tests/test_viewer.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_viewer.py:8: in <module>
    from vpype_viewer import (
vpype_viewer/__init__.py:6: in <module>
    from .engine import *
vpype_viewer/engine.py:10: in <module>
    import moderngl as mgl
E   ModuleNotFoundError: No module named 'moderngl'
======================================================== short test summary info ========================================================
ERROR tests/test_benchmarks.py
ERROR tests/test_show.py
ERROR tests/test_text.py
ERROR tests/test_viewer.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 4 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
========================================================== 4 errors in 12.21s ===========================================================
```
I then manually installed `moderngl` using pip and retried, then repeated the process after installing `PySide2` before the tests finally ran and passed successfully.
I'm unsure whether these packages are supposed to be installed as part of the Poetry install.

**Comment by abey79** [comment]
You actually need to install using `poetry install vpype -E all` so that all dependencies are installed (another thing I need to fix in the doc).

As for the pillow issue, this sounds like a Poetry/linux specific issue (see [here](https://github.com/python-poetry/poetry/issues/5104)). Apparently, upgrading to the latest poetry beta fixes the issue.

**Comment by OzHawk** [comment]
I'll leave that to others that know better than I.  I've gotten it installed for now, and can run the tests. <**thumbs up**>
