### ISSUE TITLE
Bug: `read` fails to load certain SVGs

### ISSUE THREAD

**Issue by pealco** [abey79/vpype#58]
The `read` command fails on certain SVGs.

This was the call: `vpype read -m --layer 1 voronoi.svg`

This was the error trace:

```
Traceback (most recent call last):
  File "/Users/theuser/.pyenv/versions/plotter/bin/vpype", line 8, in <module>
    sys.exit(cli())
  File "/Users/theuser/.pyenv/versions/3.7.7/envs/plotter/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/theuser/.pyenv/versions/3.7.7/envs/plotter/lib/python3.7/site-packages/vpype_cli/cli.py", line 72, in main
    return super().main(args=preprocess_argument_list(args), **extra)
  File "/Users/theuser/.pyenv/versions/3.7.7/envs/plotter/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/theuser/.pyenv/versions/3.7.7/envs/plotter/lib/python3.7/site-packages/click/core.py", line 1290, in invoke
    return _process_result(rv)
  File "/Users/theuser/.pyenv/versions/3.7.7/envs/plotter/lib/python3.7/site-packages/click/core.py", line 1224, in _process_result
    value = ctx.invoke(self.result_callback, value, **ctx.params)
  File "/Users/theuser/.pyenv/versions/3.7.7/envs/plotter/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/theuser/.pyenv/versions/3.7.7/envs/plotter/lib/python3.7/site-packages/vpype_cli/cli.py", line 118, in process_pipeline
    execute_processors(processors)
  File "/Users/theuser/.pyenv/versions/3.7.7/envs/plotter/lib/python3.7/site-packages/vpype_cli/cli.py", line 202, in execute_processors
    state = proc(state)
  File "/Users/theuser/.pyenv/versions/3.7.7/envs/plotter/lib/python3.7/site-packages/vpype/decorators.py", line 154, in global_processor
    state.vector_data = f(state.vector_data, *args, **kwargs)
  File "/Users/theuser/.pyenv/versions/3.7.7/envs/plotter/lib/python3.7/site-packages/vpype_cli/read.py", line 106, in read
    read_svg(file, quantization=quantization, simplify=not no_simplify),
  File "/Users/theuser/.pyenv/versions/3.7.7/envs/plotter/lib/python3.7/site-packages/vpype/io.py", line 163, in read_svg
    doc.flatten_all_paths(), quantization, scale_x, scale_y, offset_x, offset_y, simplify,
  File "/Users/theuser/.pyenv/versions/3.7.7/envs/plotter/lib/python3.7/site-packages/svgpathtools/document.py", line 219, in flatten_all_paths
    path_filter, path_conversions)
  File "/Users/theuser/.pyenv/versions/3.7.7/envs/plotter/lib/python3.7/site-packages/svgpathtools/document.py", line 142, in flatten_all_paths
    path = transform(parse_path(converter(path_elem)), path_tf)
  File "/Users/theuser/.pyenv/versions/3.7.7/envs/plotter/lib/python3.7/site-packages/svgpathtools/parser.py", line 91, in parse_path
    segments.closed = True
  File "/Users/theuser/.pyenv/versions/3.7.7/envs/plotter/lib/python3.7/site-packages/svgpathtools/path.py", line 2241, in closed
    if value and not self._is_closable():
  File "/Users/theuser/.pyenv/versions/3.7.7/envs/plotter/lib/python3.7/site-packages/svgpathtools/path.py", line 2219, in _is_closable
    end = self[-1].end
  File "/Users/theuser/.pyenv/versions/3.7.7/envs/plotter/lib/python3.7/site-packages/svgpathtools/path.py", line 2081, in __getitem__
    return self._segments[index]
IndexError: list index out of range
```

This is the offending SVG:
[voronoi.svg.txt](https://github.com/abey79/vpype/files/5249808/voronoi.svg.txt)

**Comment by pealco** [comment]
Here's another version of the svg generated with the same code that _does_ work.

[voronoi_working.svg.txt](https://github.com/abey79/vpype/files/5249920/voronoi_working.svg.txt)

**Comment by abey79** [comment]
Keeping this bit here just in case:
> To provide some context, I'm generating a voronoi tesselation, storing the lines as shapely LinearRings, differencing out some regions, and then applying vsk.geometry on the resulting MultiLineString.

**Comment by ithinkido** [comment]
I have noticed some similar behaviour, here is is the file before, and after. When trying to change the orientation on the processed svg ( 3 ) I am getting a similar IndexError: list index out of range error.

[circlelines_2.svg.txt](https://github.com/abey79/vpype/files/5275865/circlelines_2.svg.txt)

 [circlelines_3.svg.txt](https://github.com/abey79/vpype/files/5275861/circlelines_3.svg.txt)

**Comment by ajvdmeij** [comment]
I got the same error message. I tried this command: 
`vpype read a49n.svg scaleto 27.7cm 19cm write -p a4 --landscape -c a4gn4.svg`
See my attached file.
[a49n.svg.txt](https://github.com/abey79/vpype/files/5322853/a49n.svg.txt)

**Comment by abey79** [comment]
@pealco @ithinkido @ajvdmeij thanks for providing example files. I'm starting to look into this now. As part of this effort, I will start to populate the automated tests with a collection of SVGs to ensure that future modification do not break anything. Is it OK for you for me to add your files to said collection? These files being posted here already makes them public, but I still prefer to ask first.

**Comment by ajvdmeij** [comment]
Hi Antoine,

That is fine, of course.

Thanks for all the work,

Arjan

Op zo 4 okt. 2020 om 11:23 schreef Antoine Beyeler <notifications@github.com

**Comment by ithinkido** [comment]
Sure

**Comment by abey79** [comment]
The issue appears to be paths in the form of:
```svg
<path d="M1145.0687593814152,892.055614536064 Z"/>
```
which don't make any sense (literally: "move to X, Y then close path").

So:
- All three problematic files coming from vpype, the root cause is likely a `write` bug (such path should not be generated).
- Still not a reason for `read` to crash

I've already fixed the write issue in #69 (I'll further improve this PR with better testing before merging). For the reading bug (crash on admittedly nonsensical yet valid SVG), I'll see with the upstream project if that can be fixed (I'm using an existing lib for svg reading).

**Comment by abey79** [comment]
@ithinkido I noticed that you generated circlelines_3.svg using a command in the form of:
```
vpype read ... splitall linesimplify linemerge ... write ...
```

Note that in this case, `linesimplify` is doing nothing. After `splitall` every single path in the pipeline is just a 1-segment line, which cannot be further simplified. Of course, it doesn't (and shouldn't) matter, but this is probably not what you expected.

**Comment by abey79** [comment]
@ithinkido your file circlelines_2.svg also has something strange. Most paths it contains look similar to this:
```
<path
         style="fill:none;stroke:#0000ff;stroke-width:1.32284;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:4;stroke-dasharray:none"
         d="M 1100.42,1353.99 528.928,807.871 v 0 L 2435.8,3279.53 v 0 l -516.69,-493.75"
         id="line336" />
```

The `v 0` bits mean "draw vertical line of length 0", which effectively duplicate the previous point which is not really useful. Of course, it should not be a problem, it's just weird, but it turns out that this is what triggered the present bug.

**Comment by ithinkido** [comment]
> @ithinkido I noticed that you generated circlelines_3.svg using a command in the form of:
> 
> ```
> vpype read ... splitall linesimplify linemerge ... write ...
> ```
> 
> Note that in this case, `linesimplify` is doing nothing. After `splitall` every single path in the pipeline is just a 1-segment line, which cannot be further simplified. Of course, it doesn't (and shouldn't) matter, but this is probably not what you expected.

I am using the simplify to avoid https://github.com/abey79/vpype/issues/53

**Comment by abey79** [comment]
> I am using the simplify to avoid #53

Then you should probably use linesimplify *before* splitall.
