### ISSUE TITLE
Help with Raspberry PI installation

### ISSUE THREAD

**Issue by dtgreene** [abey79/vpype#593]
Hi, I saw that `vpype` works on the raspberry pi without the full installation but while following the steps [from the docs](https://vpype.readthedocs.io/en/latest/install.html#raspberry-pi) I've run into an error and was wondering if someone could offer any advice.

```
../../scipy/meson.build:40:0: ERROR: Command "/home/pi/.local/pipx/venvs/vpype/bin/python -c import os; os.chdir(".."); import numpy; print(numpy.get_include())" failed with status 1.

A full log can be found at /tmp/pip-install-gt92godt/scipy_504b8adcc25d4d6787ef88c7a43c8613/.mesonpy-5ob2k157/build/meson-logs/meson-log.txt
+ meson setup --prefix=/usr /tmp/pip-install-gt92godt/scipy_504b8adcc25d4d6787ef88c7a43c8613 /tmp/pip-install-gt92godt/scipy_504b8adcc25d4d6787ef88c7a43c8613/.mesonpy-5ob2k157/build --native-file=/tmp/pip-install-gt92godt/scipy_504b8adcc25d4d6787ef88c7a43c8613/.mesonpy-native-file.ini -Ddebug=false -Doptimization=2
Traceback (most recent call last):
  File "/home/pi/.local/pipx/venvs/vpype/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 144, in prepare_metadata_for_build_wheel
    hook = backend.prepare_metadata_for_build_wheel
AttributeError: module 'mesonpy' has no attribute 'prepare_metadata_for_build_wheel'
```

These are the steps I took to install:
```bash
$ sudo apt-get install python3-shapely python3-numpy python3-scipy
$ sudo apt-get install pipx
$ pipx ensurepath

# was getting another error before adding this step
$ sudo apt-get install gfortran 

$ pipx install vpype
```

Related versions:
- `Python 3.9.2`
- `pip 22.3.1`
- `pipx 0.12.3.1`

This is a completely fresh install of Raspbian GNU/Linux 11 (bullseye) running on a Raspberry PI 3b+.  I also ran the following before attempting to install:
```bash
$ sudo apt update
$ sudo apt upgrade
```

**Comment by ithinkido** [comment]
try this
```python3 -m pipx install --pip-args "--prefer-binary vpype" vpype```

**Comment by abey79** [comment]
You also need to use `--system-site-packages`:

```
pipx install vpype --system-site-packages
```

**Comment by dtgreene** [comment]
Thanks! I think it's a lot closer now.  I am getting a json.load error now:

```
Traceback (most recent call last):
  File "/usr/bin/pipx", line 11, in <module>
    load_entry_point('pipx==0.12.3.1', 'console_scripts', 'pipx')()
  File "/usr/lib/python3/dist-packages/pipx/main.py", line 496, in cli
    exit(run_pipx_command(parsed_pipx_args, binary_args))
  File "/usr/lib/python3/dist-packages/pipx/main.py", line 147, in run_pipx_command
    commands.install(
  File "/usr/lib/python3/dist-packages/pipx/commands.py", line 312, in install
    if venv.get_venv_metadata_for_package(package).package_version is None:
  File "/usr/lib/python3/dist-packages/pipx/Venv.py", line 65, in get_venv_metadata_for_package
    data = json.loads(
  File "/usr/lib/python3.9/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
TypeError: __init__() got an unexpected keyword argument 'encoding'
```

I checked out `/usr/lib/python3/dist-packages/pipx/Venv.py` which is where I think the issue comes from.  It passes an encoding argument which I saw [was removed from json.loads as of Python 3.9](https://docs.python.org/3/library/json.html#json.loads).

```
data = json.loads(
    subprocess.run(
        [
            str(self.python_path),
            "-c",
            VENV_METADATA_INSPECTOR,
            package,
            str(self.bin_path),
        ],
        stdout=subprocess.PIPE,
    ).stdout.decode(),
    encoding="utf-8", 
)
```

I'm not really familiar with Python and I wasn't able to find that in the source at all.  I'm guessing it was generated as part of a build process.

**Comment by abey79** [comment]
It might be due to your pipx being old, e.g. https://github.com/pypa/pipx/issues/702. There is a suggested solution that you might try.

**Comment by dtgreene** [comment]
Thanks! That got it working.  Here's all the steps I took:

```
# --------------------------------------
# install pipx
# --------------------------------------

# source: https://pypa.github.io/pipx/

$ python3 -m pip install --user pipx
$ python3 -m pipx ensurepath

# --------------------------------------
# install vpype
# --------------------------------------

# source: https://vpype.readthedocs.io/en/latest/install.html#raspberry-pi

$ sudo apt-get install python3-shapely python3-numpy python3-scipy gfortran libatlas-base-dev
$ pipx install vpype --system-site-packages
```

**Comment by abey79** [comment]
Great 👍🏻
