### ISSUE TITLE
OSError: [WinError 126] The specified module could not be found

### ISSUE THREAD

**Issue by Ohmarinus** [abey79/vpype#82]
Hello, new user here, but cannot get vpype to launch successfully.

Everything on this page worked for me, up until the last two steps:
https://github.com/abey79/vpype/blob/master/INSTALL.md

Recently moved from Mac Os to Windows 10 and it's a little getting used to. Almost none of the instructions worked for me so it took me an hour to figure out how to get it all installed and working.. I ran from one error into the next. Eventually it all works but I run into the error in the title when I run Vpype.

What I'm using:
Python 3.7.9
Virtualenv
Shapely-1.7.1-cp37-cp37m-win_amd64.whl (for Py 3.7)

When running vpype --help, it says:
(my-vpype-env) C:\Users\ohmar>vpype --help
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\ohmar\my-vpype-env\Scripts\vpype.exe\__main__.py", line 4, in <module>
  File "c:\users\ohmar\my-vpype-env\lib\site-packages\vpype_cli\__init__.py", line 2, in <module>
    from .blocks import *
  File "c:\users\ohmar\my-vpype-env\lib\site-packages\vpype_cli\blocks.py", line 5, in <module>
    from vpype import LengthType, VectorData, block_processor
  File "c:\users\ohmar\my-vpype-env\lib\site-packages\vpype\__init__.py", line 4, in <module>
    from .decorators import *
  File "c:\users\ohmar\my-vpype-env\lib\site-packages\vpype\decorators.py", line 8, in <module>
    from .layers import LayerType, VpypeState, multiple_to_layer_ids, single_to_layer_id
  File "c:\users\ohmar\my-vpype-env\lib\site-packages\vpype\layers.py", line 6, in <module>
    from .model import VectorData
  File "c:\users\ohmar\my-vpype-env\lib\site-packages\vpype\model.py", line 10, in <module>
    from .line_index import LineIndex
  File "c:\users\ohmar\my-vpype-env\lib\site-packages\vpype\line_index.py", line 5, in <module>
    from scipy.spatial import cKDTree as KDTree
  File "c:\users\ohmar\my-vpype-env\lib\site-packages\scipy\__init__.py", line 136, in <module>
    from . import _distributor_init
  File "c:\users\ohmar\my-vpype-env\lib\site-packages\scipy\_distributor_init.py", line 61, in <module>
    WinDLL(os.path.abspath(filename))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

Is this the place to ask for help? It's pretty intimidating, I pondered going to Stackexchange, but figured this might be too much of a 'niche' error mostly related to vpype, also couldn't find anyone with this similar issue so I decided to ask here, hope that's okay.

I hope someone has a solution.
Thanks,
Marinus

**Comment by abey79** [comment]
From the look of it, it might be because you need to download scipy from the same place as shapely, and install it the same way.

For this kind of support (and much more), I highly suggest that you join the https://drawingbots.net  discord server ([direct link](https://discordapp.com/invite/XHP3dBg)). I'm often online there and available via DMs to help you debug this situation.

**Comment by Ohmarinus** [comment]
Thanks abey79, I moved to discord. Scipy installed, but it spits out the same errors. See you there!

**Comment by abey79** [comment]
Hopefully this sort of issue will be resolved with #66
